import { useState, type Dispatch, type SetStateAction } from 'react';
import type { useAppDialog } from '../../../hooks/useAppDialog';
import { writeJsonStorageAsync } from '../../../services/persistence';
import { DEFAULT_HUELGA_MAIL_BODY,DEFAULT_HUELGA_MAIL_SUBJECT,defaultDeadlineForZone,defaultMailEnabledForZone } from './huelgasMailTemplates';
import { createZonaId, ensureDefaultZonas, type HuelgaZona } from './huelgasZones';
import { createAreaId, type HuelgaArea } from './huelgasAreas';
import { AREAS_STORAGE_KEY, ZONAS_STORAGE_KEY } from './huelgasPageModel';
type AlertFn=ReturnType<typeof useAppDialog>['alert'];
type UseHuelgaZoneMastersParams={alert:AlertFn;areas:HuelgaArea[];setAreas:Dispatch<SetStateAction<HuelgaArea[]>>;setZonas:Dispatch<SetStateAction<HuelgaZona[]>>;syncAssignmentsWithMasters:(zonas:HuelgaZona[],areas:HuelgaArea[])=>void;zonas:HuelgaZona[];};
export function useHuelgaZoneMasters({alert,areas,setAreas,setZonas,syncAssignmentsWithMasters,zonas}:UseHuelgaZoneMastersParams){
 const[zonesOpen,setZonesOpen]=useState(false);const[zoneDraft,setZoneDraft]=useState<HuelgaZona[]>([]);const[areaDraft,setAreaDraft]=useState<HuelgaArea[]>([]);const[newZoneName,setNewZoneName]=useState('');const[newAreaName,setNewAreaName]=useState('');const[newAreaZoneId,setNewAreaZoneId]=useState('');const[savingZones,setSavingZones]=useState(false);
 const openZones=()=>{setZoneDraft(ensureDefaultZonas(zonas));setAreaDraft(areas);setNewZoneName('');setNewAreaName('');setNewAreaZoneId(zonas.find(z=>z.active)?.id??'');setZonesOpen(true);};
 const closeZones=()=>{if(savingZones)return;setZonesOpen(false);setZoneDraft([]);setAreaDraft([]);setNewZoneName('');setNewAreaName('');setNewAreaZoneId('');};
 const addZone=()=>{const nombre=newZoneName.trim();if(!nombre||zoneDraft.some(z=>z.nombre.localeCompare(nombre,'es',{sensitivity:'base'})===0))return;const now=new Date().toISOString();setZoneDraft(current=>[...current,{id:createZonaId(),nombre,responsableNombre:'',responsableEmail:'',correoCc:'RELACIONES_LABORALES@metrobilbao.eus',correoActivo:defaultMailEnabledForZone(nombre),correoAsunto:DEFAULT_HUELGA_MAIL_SUBJECT,correoCuerpoHtml:DEFAULT_HUELGA_MAIL_BODY,correoPlazos:defaultDeadlineForZone(nombre),correoInstruccionesHabituales:'',plantillaExcelUrl:'',plantillaExcelNombrePatron:`${nombre} - Seguimiento huelga {{FECHA_HUELGA_ARCHIVO}}.xlsx`,active:true,createdAt:now,updatedAt:now}].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})));setNewZoneName('');};
 const updateZone=(id:string,field:'nombre'|'responsableNombre'|'responsableEmail'|'correoCc'|'correoActivo'|'correoAsunto'|'correoCuerpoHtml'|'correoPlazos'|'correoInstruccionesHabituales'|'plantillaExcelNombrePatron'|'active',value:string|boolean)=>setZoneDraft(current=>current.map(z=>z.id===id?{...z,[field]:value,updatedAt:new Date().toISOString()}:z));
 const addArea=()=>{const nombre=newAreaName.trim();if(!nombre||!newAreaZoneId)return;if(areaDraft.some(a=>a.zonaId===newAreaZoneId&&a.nombre.localeCompare(nombre,'es',{sensitivity:'base'})===0))return;const now=new Date().toISOString();setAreaDraft(current=>[...current,{id:createAreaId(),nombre,zonaId:newAreaZoneId,active:true,createdAt:now,updatedAt:now}].sort((a,b)=>a.zonaId.localeCompare(b.zonaId,'es',{sensitivity:'base'})||a.nombre.localeCompare(b.nombre,'es',{sensitivity:'base'})));setNewAreaName('');};
 const updateArea=(id:string,field:'nombre'|'zonaId'|'active',value:string|boolean)=>setAreaDraft(current=>current.map(a=>a.id===id?{...a,[field]:value,updatedAt:new Date().toISOString()}:a));
 const saveZones=async()=>{const normalizedZones=zoneDraft.map(z=>({...z,nombre:z.nombre.trim(),responsableNombre:z.responsableNombre.trim(),responsableEmail:z.responsableEmail.trim(),correoCc:z.correoCc.trim(),correoAsunto:z.correoAsunto.trim(),correoPlazos:z.correoPlazos.trim(),correoInstruccionesHabituales:z.correoInstruccionesHabituales.trim(),plantillaExcelNombrePatron:z.plantillaExcelNombrePatron.trim()}));if(normalizedZones.some(z=>!z.nombre)){await alert('Todas las zonas deben tener un nombre.',{title:'Revisa las zonas',type:'warning'});return;}const zoneNames=new Set<string>();for(const z of normalizedZones){const key=z.nombre.toLocaleLowerCase('es-ES');if(zoneNames.has(key)){await alert(`La zona “${z.nombre}” está duplicada.`,{title:'Revisa las zonas',type:'warning'});return;}zoneNames.add(key);}const normalizedAreas=areaDraft.map(a=>({...a,nombre:a.nombre.trim()}));if(normalizedAreas.some(a=>!a.nombre||!a.zonaId)){await alert('Todas las áreas deben tener nombre y una zona asignada.',{title:'Revisa las áreas',type:'warning'});return;}const areaNames=new Set<string>();for(const a of normalizedAreas){const key=`${a.zonaId}::${a.nombre.toLocaleLowerCase('es-ES')}`;if(areaNames.has(key)){await alert(`El área “${a.nombre}” está duplicada dentro de la misma zona.`,{title:'Revisa las áreas',type:'warning'});return;}areaNames.add(key);}setSavingZones(true);const zoneResult=await writeJsonStorageAsync(ZONAS_STORAGE_KEY,normalizedZones);if(!zoneResult.ok){setSavingZones(false);await alert(zoneResult.message||'No se ha podido guardar el maestro de zonas.',{title:'Error de guardado',type:'error'});return;}const areaResult=await writeJsonStorageAsync(AREAS_STORAGE_KEY,normalizedAreas);setSavingZones(false);if(!areaResult.ok){await alert(areaResult.message||'No se ha podido guardar el maestro de áreas.',{title:'Error de guardado',type:'error'});return;}setZonas(normalizedZones);setAreas(normalizedAreas);syncAssignmentsWithMasters(normalizedZones,normalizedAreas);closeZones();};
 return{addArea,addZone,areaDraft,closeZones,newAreaName,newAreaZoneId,newZoneName,openZones,saveZones,savingZones,setNewAreaName,setNewAreaZoneId,setNewZoneName,updateArea,updateZone,zoneDraft,zonesOpen};
}
