name: Ejecutar tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests manuales
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Comprobar versiones
        run: |
          node --version
          npm --version
          npx eslint --version

      - name: Ejecutar lint
        run: npm run lint

      - name: Ejecutar tests
        run: npm run test

      - name: Compilar app
        run: npm run build
